# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\"|\n\x08NodeInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0b\n\x03mac\x18\x02 \x01(\t\x12\x0b\n\x03ram\x18\x03 \x01(\x05\x12\x0b\n\x03\x63pu\x18\x04 \x01(\t\x12\x11\n\tbandwidth\x18\x05 \x01(\x05\x12\x0f\n\x07storage\x18\x06 \x01(\x05\x12\x0b\n\x03hdd\x18\x07 \x01(\t\x12\x0c\n\x04port\x18\x08 \x01(\x05\"+\n\nNodeStatus\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x11\n\tis_active\x18\x02 \x01(\x08\"l\n\tFileChunk\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\x0c\x12\x14\n\x0c\x63hunk_number\x18\x03 \x01(\x05\x12\x14\n\x0ctotal_chunks\x18\x04 \x01(\x05\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\t\";\n\x0b\x46ileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x1a\n\x12requesting_node_ip\x18\x02 \x01(\t\"E\n\x0c\x46ileLocation\x12\x0f\n\x07node_ip\x18\x01 \x01(\t\x12\x11\n\tnode_port\x18\x02 \x01(\x05\x12\x11\n\tis_online\x18\x03 \x01(\x08\"\x1d\n\x08\x46ileList\x12\x11\n\tfilenames\x18\x01 \x03(\t\"8\n\x14RegistrationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\")\n\x11HeartbeatResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\"M\n\x0eUploadResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x19\n\x11replication_count\x18\x03 \x01(\x05\"\x07\n\x05\x45mpty2\x9c\x03\n\x11\x43ontrollerService\x12\x46\n\x0cRegisterNode\x12\x14.controller.NodeInfo\x1a .controller.RegistrationResponse\x12\x42\n\tHeartbeat\x12\x16.controller.NodeStatus\x1a\x1d.controller.HeartbeatResponse\x12\x41\n\nUploadFile\x12\x15.controller.FileChunk\x1a\x1a.controller.UploadResponse(\x01\x12@\n\x0c\x44ownloadFile\x12\x17.controller.FileRequest\x1a\x15.controller.FileChunk0\x01\x12@\n\x0bRequestFile\x12\x17.controller.FileRequest\x1a\x18.controller.FileLocation\x12\x34\n\tListFiles\x12\x11.controller.Empty\x1a\x14.controller.FileListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NODEINFO']._serialized_start=32
  _globals['_NODEINFO']._serialized_end=156
  _globals['_NODESTATUS']._serialized_start=158
  _globals['_NODESTATUS']._serialized_end=201
  _globals['_FILECHUNK']._serialized_start=203
  _globals['_FILECHUNK']._serialized_end=311
  _globals['_FILEREQUEST']._serialized_start=313
  _globals['_FILEREQUEST']._serialized_end=372
  _globals['_FILELOCATION']._serialized_start=374
  _globals['_FILELOCATION']._serialized_end=443
  _globals['_FILELIST']._serialized_start=445
  _globals['_FILELIST']._serialized_end=474
  _globals['_REGISTRATIONRESPONSE']._serialized_start=476
  _globals['_REGISTRATIONRESPONSE']._serialized_end=532
  # _globals['_HEARTBEATRESPONSE']._serialized_start=534
  # _globals['_HEARTBEATRESPONSE']._serialized_end=575
  _globals['_UPLOADRESPONSE']._serialized_start=577
  _globals['_UPLOADRESPONSE']._serialized_end=654
  _globals['_EMPTY']._serialized_start=656
  _globals['_EMPTY']._serialized_end=663
  _globals['_CONTROLLERSERVICE']._serialized_start=666
  _globals['_CONTROLLERSERVICE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
